---
- name: Enviar archivos por rsync
  hosts: all
  gather_facts: yes
  tasks:
    - name: Enviar archivos mediante rsync
      ansible.posix.synchronize:
        src: "{{ item }}"
        dest: "/opt/backups_ventana/{{ ansible_hostname }}/{{ folder_destino }}"
        remote_src: no
        archive: yes
        compress: yes
      with_items:
        - "{{ file1 }}"
        - "{{ file2 }}"
        - "{{ file3 }}"
      delegate_to: "{{ ip_backup }}"
      when: item | length > 0
