- name: Gestión de usuarios Linux para AWX
  hosts: all
  become: true
  vars:
    default_shell: '/bin/bash'
    sudoers_file: '/etc/sudoers.d/ansible-managed'

  tasks:
    - name: Validar que el nombre de usuario no esté vacío
      fail:
        msg: "El nombre de usuario es requerido"
      when: not username is defined or username == ''
      tags:
        - always
        - validation

    - name: Validar que la contraseña no esté vacía para crear o modificar
      fail:
        msg: "La contraseña es requerida para crear o modificar usuarios"
      when: 
        - action in ['create', 'modify_password']
        - not password is defined or password == ''
      tags:
        - always
        - validation

    - name: Crear grupo primario del usuario
      group:
        name: "{{ username }}"
        state: "{{ state }}"
      when: action == 'create'
      tags:
        - users
        - groups

    - name: Gestionar usuario
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') if password is defined else omit }}"
        shell: "{{ default_shell }}"
        group: "{{ username }}"
        state: "{{ state }}"
        update_password: "{{ 'always' if action == 'modify_password' else 'on_create' }}"
      when: action != 'delete'
      tags:
        - users

    - name: Eliminar usuario
      user:
        name: "{{ username }}"
        state: absent
        remove: yes
      when: action == 'delete'
      tags:
        - users

    - name: Agregar entrada sudo al archivo
      lineinfile:
        path: "{{ sudoers_file }}"
        line: "{{ username }} ALL=(ALL) {{ 'NOPASSWD:' if sudo_nopasswd | bool else '' }} ALL"
        state: present
        create: yes
        validate: 'visudo -cf %s'
        mode: '0440'
      when: 
        - action != 'delete'
        - is_sudo | bool
      tags:
        - sudo

    - name: Eliminar entrada sudo del archivo
      lineinfile:
        path: "{{ sudoers_file }}"
        regexp: "^{{ username }} "
        state: absent
        validate: 'visudo -cf %s'
      when: action == 'delete'
      tags:
        - sudo
