---
- name: Sincronizar Sofia + DB
  hosts: sofia
  become: yes
  gather_facts: no

  vars:
    path_erp_origen: "/mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_origen }}.colmedicos.com/public_html"
    path_erp_destino: "/mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_destino }}.colmedicos.com/public_html"
    path_bd_origen: "/mnt/colmedicos/mysqlserver/{{ instancia_origen }}"
    path_bd_destino: "/mnt/colmedicos/mysqlserver/{{ instancia_destino }}"
        
  tasks:
    - name: Transferir ERP
      shell: |
         rsync -avh --exclude='erp/pco/SOFIA' {{ path_erp_origen }}/erp {{ path_erp_destino }}
    
    - name: Transferir index.snt
      shell: |
         rsync -avh --exclude='erp/pco/SOFIA' {{ path_erp_origen }}/index.snt {{ path_erp_destino }}          

    - name: Transferir base de datos
      shell: |
         rsync -avh {{ path_bd_origen }}/ {{ path_bd_destino }}

    - name: Permisos para ERP
      ansible.builtin.file:
        path: "{{ path_erp_destino }}/erp"
        mode: '0777'
        recurse: yes
        owner: root
        group: root
        follow: no
   
    - name: Permisos para MYSQL
      ansible.builtin.file:
        path: "{{ path_bd_destino }}"
        mode: '0777'
        recurse: yes
        owner: mysql
        group: mysql
        follow: no

    - name: Crear enlace simbólico SOFIA
      ansible.builtin.file:
        src: ".."
        dest: "{{ path_erp_destino }}/erp/pco/SOFIA"
        state: link

    - name: Modificar variables de conexión en lib.snt
      ansible.builtin.replace:
        path: "{{ path_erp_destino }}/erp/inc/lib.snt"
        regexp: '(\$BaseDatos=")[^"]*(";)'
        replace: '\1{{ instancia_destino }}\2'
      register: result_lib_bd

    - name: Modificar contraseña de la base de datos en lib.snt
      ansible.builtin.replace:
        path: "{{ path_erp_destino }}/erp/inc/lib.snt"
        regexp: '(\$PasswordBD=")[^"]*(";)'
        replace: '\1{{ password_db_rednal }}\2'
      register: result_lib_pass   
  
    - name: Modificar variables de conexión en configuracion.php
      ansible.builtin.replace:
        path: "{{ path_erp_destino }}/erp/pco/core/configuracion.php"
        regexp: '(^\s*\$BaseDatos=).*'
        replace: '\1 "{{ instancia_destino }}"'
      register: result_conf_bd

    - name: Modificar contraseña de la base de datos en configuracion.php
      ansible.builtin.replace:
        path: "{{ path_erp_destino }}/erp/pco/core/configuracion.php"
        regexp: '(^\s*\$PasswordBD=).*'
        replace: '\1 "{{ password_db_rednal }}"'
      register: result_conf_pass
      
    
    - name: Eliminar archivos en los directorios ERP
      shell: "rm -rf {{ path_erp_destino }}/erp/{{ item }}/*"
      with_items:
        - anx
        - csv
        - ecg
        - err
        - ext
        - fin
        - inf
        - int
        - lab
        - log
        - nom
        - opt
        - ost
        - pic
        - psi
        - qrc
        - sgc
        - sgn
        - sop
        - spi
        - vox
      ignore_errors: yes 
         
 
  
       

        
