---
- name: Sincronizar Sofia + DB
  hosts: sofia
  become: yes
  gather_facts: no
        
  tasks:
   
    - name: Transferir ERP
      shell: |
         rsync -avh /mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_origen }}.colmedicos.com/public_html/erp/
         /mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_destino }}.colmedicos.com/public_html/
    
              
    - name: Transferir base de datos
      shell: |
         rsync -avh /mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_origen }}.colmedicos.com/public_html/erp/
         /mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_destino }}.colmedicos.com/public_html/

    - name: Permisos para ERP
      ansible.builtin.file:
        path: /mnt/colmedicos/webserver/colmedicos/domains/{{ instancia_destino }}.colmedicos.com/public_html/erp
        mode: '0777'
        recurse: yes
        owner: root
        group: root
   
    - name: Permisos para MYSQL
      ansible.builtin.file:
        path: /mnt/colmedicos/webserver/colmedicos/domains/mysqlserver/{{ instancia_destino }}
        mode: '0777'
        recurse: yes
        owner: mysql
        group: mysql
